### PR TITLE
Studyng

### PR DESCRIPTION
**Pull request by VadimSMG**
Refactoring Terraform code. Split one main.tf onto main.tf, variables.tf and outputs.tf

### CODE REVIEW

**Comment by danliaudan** [comment]
Good, code is pretty much clear. For low-scale project for single elements you may also use name for resources "this", but it is not neccessary. 

I give you some notes, they're not crucial but check it please :)

**Comment by VadimSMG** [comment]
Did I need to put "this" before or instead resource name?

**Comment by danliaudan** [comment]
It just name convention. I mean, you should write "this" instead resource name. In different cases for different companies/projects there are different name convention, keep in mind that this name conventio should be understandable for you and simplifies development of infrastructure

**Comment by VadimSMG** [comment]
Okay, thank you!

**Pull request merged**
